[package]
name = "py-mandelbrot-rs"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_mandelbrot_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
num = "0.4.3"
rayon = "1.11.0"
