[project]
name = "py-mandelbrot-rs"
version = "0.1.0"
description = "Calculate a visualization of the Mandelbrot set"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
]
